services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda-eletronica
    ports:
      - "4200:80"
    depends_on:
      - jsonserver

  jsonserver:
    image: clue/json-server
    container_name: json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json # Ensure db.json exists in the same directory as this file
    command: -p 3000 /data/db.json