services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda-eletronica
    ports:
      - "4200:80"
    depends_on:
      - jsonserver

  jsonserver:
    image: clue/json-server
    container_name: json-server
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json 
