services:
  frontend:
    image: agenda-frontend:1.0
    container_name: agendinha
    ports:
      - "4200:80"
    depends_on:
      - jsonserver

  jsonserver:
    image: clue/json-server
    container_name: json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
    command: -p 3000 /data/db.json